### ISSUE TITLE
Create VCF-class object

### ISSUE THREAD

**Issue by NinaW2021** [gerstung-lab/deepSNV#13]
Hi,

I'm trying to create a VCF-class object using:

   summary(
      object,
      sig.level = 0.05,
      adjust.method = "bonferroni",
      fold.change = 1,
      value = c("VCF")
  )

but keep getting the following error: "Error in metadata(v)$header@header$META["date", 1] <- paste(Sys.time()) : 
  incorrect number of subscripts on matrix"

Creating the data.frame works... Please could you let me know what this error means and how I can solve it?

Thanks!

**Comment by antoniocollesei** [comment]
Hello,

I am having the same issue as above, in both environments I am currently working on. Pasting the session info, as it can be useful:
**R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)**
&
**R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS**

Thank you!
